### ISSUE TITLE
OpenCV retorna erro ao executar o método cvtColor() 

### ISSUE THREAD

**Issue by keikoligia** [keikoligia/educacess#4]
***RESOLVIDO***

Mensagem de erro:

Traceback (most recent call last):
  File "c:\Projetos\educacess\frames\main.py", line 80, in <module>
    luv = cv2.cvtColor(frame, cv2.COLOR_BGR2LUV)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

~pesquisei sobre esse erro e as pessoas falam que é porque o caminho do vídeo tá errado, mas o programa tá lendo o vídeo normal~

**Comment by keikoligia** [comment]
Novos erros:

Traceback (most recent call last):
  File "c:\Projetos\educacess\frames\main.py", line 118, in <module>
    plt.savefig(dir + 'plot.png')
  File "C:\Users\LK\AppData\Roaming\Python\Python38\site-packages\matplotlib\pyplot.py", line 966, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\Users\LK\AppData\Roaming\Python\Python38\site-packages\matplotlib\figure.py", line 3005, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\LK\AppData\Roaming\Python\Python38\site-packages\matplotlib\backend_bases.py", line 2255, in print_figure
    result = print_method(
  File "C:\Users\LK\AppData\Roaming\Python\Python38\site-packages\matplotlib\backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\LK\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_agg.py", line 509, in print_png
    mpl.image.imsave(
  File "C:\Users\LK\AppData\Roaming\Python\Python38\site-packages\matplotlib\image.py", line 1616, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Python38\lib\site-packages\PIL\Image.py", line 2232, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './extract_result/plot.png'
